config/bindings.vim
lib/functions.vim

Example:
Say a file `some/package/with_a_test.go` is being edited. When
`RunTests(some/package/with_a_test.go)` is called it will pass the
package of the currently edited test file, i.e. `some/package`, to either
`script/test` or `ginkgo` by default.
I have found this useful while deveoping in go so though I would
contribute.
Sorry there are no tests for this, was not sure how to test this as
there are no exsisting tests (that I could see).

Add support for running go lang tests with ginkgo

---

install

These are a few changes I had to make to the install script on my machine in
order to make it finish successfully.
* For some reason the `\e` escape code didn't work for me. I had to change it
to the explicit `\033`.
* I have Git configured to always use SSH URLs when cloning which confuses `go
get`. It complains that the origin is different to what is expected. Adding
the `-f` flag fixes this.

Install Script Changes

---

Plug.vim

Go auto-complete seems to work a lot better with this plugin installed as well. It might just be my environment though.

Adds gocomplete

---

config/plugin/syntastic.vim
vimrc

- Pylint is too strict. It raises warning for things like missing
docstrings, which distract from actual issues.
- Flake8 is a decent replacement that combines PyFlakes, PEP8, and a
complexity checker.

Configure syntastic to use flake8 for python files

---

Plug.vim
config/plugin/rust.vim
vimrc

Rust language support is missing. The plugin provides a basic syntax highlighting and code formatting.

Add rust plugin

---

bin/install

This will make gd work without running :GoInstallBinaries first.

Add rogpeppe/godef to go packages list

---

config/lang/golang.vim

Signed-off-by: James Myers <jmyers@pivotal.io>

Don't show auto type info in go when the cursor is over a line.

---

.travis.yml
bin/install

This forces non interactive if stdin is null, and also makes travis depend on it as a way of testing it works.

Detect if we're in an interactive shell

---

config/plugin/fzf.vim

Trying to use ,F was giving an error "No command FZFBtags."  It looks like the 't' of 'tags' needs to be capitalized.

Fix capitalization in FZFBTags command

---

config/crontab.vim
vimrc

If crontabs are not edited in place, the edit fails with:
crontab: temp file must be edited in place

Skip backups for crontab

---

config/basic.vim

This mode makes it so that visual selections will automatically be copied into the system clipboard
http://superuser.com/questions/348207/prevent-macvim-copying-every-visual-selection-to-clipboard

Remove guioptions 'a' mode

---

bin/install

When this repo is a submodule, `.git` will be a file instead of a directory.

Check if .git is an existing file or directory

---

lib/autocommands.vim

By default it displays on the bottom-right if there is a vertical split, which makes long go errors not visible
Signed-off-by: Ben Moss <bmoss@pivotal.io>

Always show quickfix in full-width bottom split

---

Plug.vim

when I run `vim-update`, I get the following error.
```
[vim-plug] Invalid argument: matchit.zip (implicit `vim-scripts' expansion is deprecated)
```
Please see https://github.com/junegunn/vim-plug/commit/f7e6a86807a1f0be7257620a8c425e1a32f877bb

Fix implicit `vim-scripts' expansion is deprecated error

---

lib/functions.vim

Will run "npm test <filename>" if package.json exists; 
Defaults to "jasmine <filename>" otherwise.

Add support to javascript tests with jasmine

---

Plug.vim

The `for: go` clause when trying to `do: GoInstallBinaries` in Plug.vim
was causing it not to run during installation.

Actually run GoInstallBinaries during install

---

README.md

For convenience, adding a link to the git repo for `ag` where it's mentioned as a dependency.

Add link to `ag` in README

---

bin/install

This is recommended by these docs: https://github.com/zchee/deoplete-jedi/wiki/Setting-up-Python-for-Neovim
Trying to install without this flag was giving me a permission failure
over
`/usr/local/lib/python2.7/site-packages/six-1.10.0.dist-info/DESCRIPTION.rst`

Install neovim python plugins in home dir

---

README.md

- `lua` is no longer required so this doesn't make sense any more.
- add note about macOS High Sierra pre-installed VIM
Note: the ubuntu package `vim-nox` may no longer be correct/required given that `lua` is no longer needed.

Remove the `--with-lua` instructions for brew

---

README.md

The vim version is useable but system python doesn't have `pip`. Resolving this issue seems to be a bit of a goose chase. For now it seems best to use the `brew` provided vim.

Remove note about High Sierra vim

---

config/colors.vim

Not just 'screen*'.
I use `set -g default-terminal "tmux-256color"` in order to enable support for
italics inside tmux. This patch sets t_8f and t_8b in configurations like mine.

Improve color rendering for 'tmux*' terminals

---

bin/install

Globally install neovim pip package. I think this makes sense given that the
python-greenlet package is removed as root.
I'm not sure what to do in the non-Arch cases. For Homebrew users on macOS, pip
can be run as non-root and without `--user` due to the writeability of
/usr/local. On most Linux systems, pip without `--user` will not run as
non-root. Some users will want to install the neovim package as root, some will
want to use `--user`. Perhaps a flag? What do you think?
I'm not sure testing for the presence of virtualenv to decide this makes sense,
as users often won't have a virtualenv loaded, causing the non-`--user` case to
fail. I might be massively wrong about that, I don't use Python much at all.
Additionally, use `--needed` with `pacman -S` to avoid reinstallation.

Fix installation on Arch Linux

---

UltiSnips/go.snippets

Golang developers often have to check for errors and handle them
appropriately. Writing code similar to
```golang
if err != nil {
// do something fancy here
}
```
is very common and therefore it would be great to have a shortcut for
that.
There are some error handling snippets existing [here](https://github.com/fatih/vim-go/blob/0b7e453774aec11e9d07b6d9126e3d583c6ac2ce/gosnippets/snippets/go.snip#L129-L173) but I don't really feel them to be "general purpose" as they are doing something concrete to handle the error (e.g. panic, log, fail a test)

Introduce the `iferr` golang snippet

---

config/lang/markdown.vim
config/plugin/nerdtree.vim

Recent travis builds fail with 
```
config/lang/markdown.vim:1:1: autocmd should execute in an augroup or execute with a group (see :help :autocmd)
config/plugin/nerdtree.vim:11:1: autocmd should execute in an augroup or execute with a group (see :help :autocmd)
```
This commit fixes the error above via putting `autocmd`s into `autogroup`s in the aforementioned files

Put markdown and nerdtree autocmds in groups

---

bin/install

The github.com/mdempsky/gocode fork of github.com/nsf/gocode is
installed, which dropped support for drop-cache in
https://github.com/mdempsky/gocode/commit/e117c263fb7092eedd7cab24f41d90a9d76bd23a
With this use of drop-cache present, an install of vimfiles errors
after installing go binaries with:
```
gocode: unknown subcommand: "drop-cache"
Run 'gocode -help' for usage.
```

Don't run missing gocode "drop-cache" command

---

bin/install

Any bash function will implicitly return the value of the last evaluated expression.
From the [bash documentation](https://www.gnu.org/software/bash/manual/html_node/Shell-Functions.html#Shell-Functions)
> When executed, the exit status of a function is the exit status of the last command executed in the body.
When go is not installed the expression `has_go && setup_go_dependencies` will return non zero, as it is the last expression of `main` it also returns non zero. This in turn causes the script to return non zero. This gives the appearance the script has failed even though it succeeded.
The simple solution is to call `return 0` at the bottom of the main function.

ensure install returns success when go not installed

---

README.md

A couple months ago the neovim python package was renamed and `broke pip install --upgrade neovim`
This PR adds a warning to the README of this repo but doesn't resolve the underlying issue (that `install` will break a Vimfiles setup that previously had `neovim` installed when it [runs `sudo $PIP install --upgrade neovim`](https://github.com/luan/vimfiles/blob/de7e15c9560a3653cdfeb12a4f9e082e18a945a1/bin/install#L229-L238).
I propose an additional change (not included in this PR pending discussion) to `install` that would detect a previously installed `neovim` package, uninstall it (and potentially any `pynvim` that is present), and directly install `pynvim`. This could potentially be achieved with `$PIP show neovim`.

Add warning about the pynvim package name change

---

config/basic.vim

Due to the following security issue with modeline (patched in latest versions of Vim and Nvim) it is recommended to disable modeline and use the secure modeline plugin or other configuration tools instead.
see https://github.com/numirias/security/blob/master/doc/2019-06-04_ace-vim-neovim.md

Disable modeline

---

bin/install
config/lang/golang.vim
config/plugin/ale.vim

Gometalinter has been deprecated in favour of `golangci-lint`. `vim-go` has even drop support for it: https://github.com/fatih/vim-go/pull/2494

Change linter to golangci-lint
